### ISSUE TITLE
Error importing SimPEG.Regularization

### ISSUE THREAD

**Issue by fourndo** [simpeg/simpegEM1D#34]
Need to update for lower case regularization

![image](https://user-images.githubusercontent.com/2406426/63144160-77fc2380-bfa6-11e9-9e7a-93207465c657.png)

**Comment by fourndo** [comment]
@sgkang Can we fix this quick? 
I am supposed to give a training tomorrow morning. Would be great if we don't have to fiddle with files.
Thanks mate.

**Comment by fourndo** [comment]
Looks like it is already done in the codebase. Do we need to update pip?

**Comment by sgkang** [comment]
@fourndo yes, I'll deploy the current master into pypi

**Comment by sgkang** [comment]
this should be fixed now. 
let me know if there are still issues with this.

**Comment by sgkang** [comment]
fixed. current pypi version is 0.0.18a

**Comment by fourndo** [comment]
@sgkang thanks man

**Comment by prisae** [comment]
This still is an issue for me. Should it work now?

**Comment by prisae** [comment]
I've installed both `SimPEG` and `simpegEM1D` via `pip install -U`; the error I get by importing `simpegEM1D` is:
```
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-8164c3eb5ff5> in <module>
      1 from SimPEG import *
----> 2 from simpegEM1D import (
      3     EM1D, EM1DSurveyTD, Utils1D,
      4     set_mesh_1d, skytem_LM_2015
      5 )

~/anaconda3/lib/python3.7/site-packages/simpegEM1D/__init__.py in <module>
     28     set_mesh_1d, run_simulation_FD, run_simulation_TD
     29 )
---> 30 from .Regularization import (
     31     LateralConstraint, get_2d_mesh
     32 )

~/anaconda3/lib/python3.7/site-packages/simpegEM1D/Regularization.py in <module>
      1 import scipy as sp
      2 import numpy as np
----> 3 from SimPEG.Regularization import Sparse, SparseSmall, SparseDeriv
      4 from SimPEG import Mesh, Utils
      5 

ModuleNotFoundError: No module named 'SimPEG.Regularization'
```

**Comment by leonfoks** [comment]
I just installed everything to work through the notebooks you are helping me with and I didn't have this issue.

**Comment by prisae** [comment]
Hm. I found it weired too. But it keeps failing on me. What version of Python are you using?

**Comment by prisae** [comment]
My scooby-report:
```
In [6]: scooby.Report(SimPEG)                                                   
Out[6]: 

--------------------------------------------------------------------------------
  Date: Fri Nov 15 20:46:28 2019 CET

             Linux : OS
                 4 : CPU(s)
            x86_64 : Machine
             64bit : Architecture
           15.5 GB : RAM
           IPython : Environment

  Python 3.7.4 (default, Aug 13 2019, 20:35:49)  [GCC 7.3.0]

            0.12.0 : SimPEG
            1.17.3 : numpy
             1.3.1 : scipy
             7.9.0 : IPython
             3.1.1 : matplotlib
             0.4.3 : scooby

  Intel(R) Math Kernel Library Version 2019.0.4 Product Build 20190411 for
  Intel(R) 64 architecture applications
--------------------------------------------------------------------------------
```

**Comment by leonfoks** [comment]
I guess i'm a little behind in a couple of things

Fri Nov 15 12:49:18 2019 MST
--
Darwin | OS | 8 | CPU(s) | x86_64 | Machine
64bit | Architecture | Jupyter | Environment
Python 3.7.3 \| packaged by conda-forge \| (default, Jul 1 2019, 14:38:56) [Clang 4.0.1 (tags/RELEASE_401/final)]
0.12.0 | SimPEG | 1.16.3 | numpy | 1.2.1 | scipy
7.9.0 | IPython | 3.0.3 | matplotlib | 0.4.3 | scooby

**Comment by prisae** [comment]
OK, the issue might be the following': on GitHub, the latest release is 0.0.17 for simpegEM1D, but on PyPi, it is 0.0.16. So it looks like the latest release got never deployed to PyPi. I'll try to install from Github then...

**Comment by prisae** [comment]
That works.

So the issue is that the version of `simpegEM1D` on PyPi is outdated.

**Comment by asf108** [comment]
Hello,
im trying to use simpegEM1D, but so far i think i have the same probles discussed here,
first, i reinstalled both SimPEG and simpegEM1D to make sure that i do have the current versions,
i have the SimPEG 14.3  and simpegEM1D 0.0.18a0,

when i try to call it, i had the following problem:

**import simpegEM1D
Traceback (most recent call last):

  File "<ipython-input-8-b0d73dbf7a81>", line 1, in <module>
    import simpegEM1D

  File "C:\Users\Usuario\Anaconda3\lib\site-packages\simpegEM1D\__init__.py", line 1, in <module>
    from .EM1D import EM1D

  File "C:\Users\Usuario\Anaconda3\lib\site-packages\simpegEM1D\EM1D.py", line 1, in <module>
    from SimPEG import Maps, Utils, Problem, Props

ImportError: cannot import name 'Maps' from 'SimPEG' (C:\Users\Usuario\Anaconda3\lib\site-packages\SimPEG\__init__.py)**

i think it maybe the uppercase letters, as the current version of SimPEG uses lowercase

There is a way to fix this?

**Comment by asf108** [comment]
Sorry about the last question,
it works with an older version of SimPEG  (0.13.1) and with a version of empymod 1.10.6 or older.

**Comment by geophylika** [comment]
I got ImportERROR about "create_nested_mesh"
  File "d:\geoapps-develop\geoapps\drivers\components\data.py", line 25, in <module>
    from SimPEG.utils.drivers import create_nested_mesh
ImportError: cannot import name 'create_nested_mesh' from 'SimPEG.utils.drivers' (d:\ProgramData\Anaconda3\envs\geoapps\lib\site-packages\SimPEG\utils\drivers\__init__.py)

There is a way to fix this?

**Comment by prisae** [comment]
I forgot to close this way back. Definitely outdated, particularly with the eminent merge of simpegEM1D into SimPEG.

@geophylika: I don't think this is the right thread for your question. Do you mind posting it on https://simpeg.discourse.group ?
